---
title: "Chapter 1: Cross-city drivers of urban forest regulatory ecosystem services"
output: 
  word_document:
    keep_md: true 
    reference_docx: style.docx
  csl: ecology.csl
bibliography: PhD.bib
fontsize: 12pt
---

Ecosystem service capacity is determined by many factors, hereafter referred to as drivers. For example, an urban tree's capacity to provide temperature regulation to its citizens is partially driven by its leaf area [@rahman2020]. Quantifying and understanding drivers of ecosystem services is an important strategy for planning cities that are healthy and equitable. If the magnitude and direction of the drivers' influences are known, governments, NGOs, and other interested parties can begin planning for maximum ecosystem service delivery before ever planting a tree. Most ecosystem studies to date assess ecosystem services in one city [@ziter2016]. Although a single city approach is extremely useful for understanding fine-scale intricacies of ecosystem services, it does not allow for the identification of common drivers of ecosystem service capacity.  

To test the roles of different drivers of urban forest ecosystem service capacity, we propose a framework of "cross-city" and "location-specific" drivers. We would expect location-specific drivers to be unique to individual places and influence ecosystem services on a specific spatial scale. We would expect different cities to have various location-specific drivers that influence one city's provision of ecosystem services but not another. For example, different management practices in different municipalities may lead to different tree sizes, and thus result in a location-specific driver of aboveground carbon storage. Conversely, cross-city drivers are drivers that influence ecosystem services in multiple locations and across spatial scales. These are processes that consistently influence the provision of ecosystem services, although the magnitude may shift depending on spatial context. For example, biodiversity of the urban forest may influence the provision of ecosystem services, regardless of which city or at what scale you are investigating. Our study's goals are to identify and differentiate between cross-city and location-specific drivers of urban forest ecosystem services using a cross-city, multi-scale, multi-service approach. Specifically, we will ask:

> What are the cross-city drivers of regulatory ecosystem services provided by the urban forest in Canadian temperate cities?

All ecosystem processes are influenced by scale. The highly heterogeneous nature of cities requires a multi-scale approach. The drivers and capacity of ecosystem services by the urban forest are all dependent on the spatial scale of analysis. Factors such as biodiversity, parcel size, spatial distribution of trees, density, soil type, scale of management and more determine the production and subsequent delivery of ecosystem services by the urban forest (REFS). Further, relevant scales may differ depending on the driver or service being examined. For example, the relevant scales of urban heat island mitigation by trees, e.g., extremely fine-scale measurements under tree canopies and very large scale measurements at the whole-city level, may differ from the relevant scales for air pollution mitigation, e.g., the combined effect of trees at the neighbourhood scale. Thus, to gain a comprehensive understanding of how ecosystem services and their drivers are operating, we must take a multi-scale approach. To date, there have been few studies that take a multi-scale and multi-service approach (but see REFS for examples). Further, most multi-scale studies take place in a single city, which provides valuable information for that specific location but limits the ability to extrapolate the trends in services and drivers examined.  


# Approach  
We will use existing, publicly available data to test ecosystem services and their drivers in seven major temperate Canadian cities: Vancouver, Calgary, Winnipeg, Toronto, Ottawa, Montreal, Halifax. We will test drivers of ecosystem services at three scales within the cities, fine-scale (street level), medium-scale (neighbourhood level), and large scale (city level). Using remotely sensed data we will measure proxies for three regulatory ecosystem services, temperature regulation, carbon sequestration, and air pollution mitigation. Using a combination of urban tree inventories, land cover maps, and census data we will have three groups of independent variables: natural, built infrastructure, and human demographics. Our natural variables will include biodiversity, tree size, and tree density. Built infrastructure variables will include road width and building density. Finally, our human demographics will include population density and socioeconomic status. The goal of this study is to determine common drivers of urban forest ecosystem services in Canadian cities.

# Status  
We are currently in the data collection stage.

### References