---
title: "Introduction"
output: 
  word_document:
    keep_md: true 
    reference_docx: style.docx
  csl: ecology.csl
bibliography: PhD.bib
fontsize: 12pt
---

Urban landscapes are a complex combination of natural, physical, social, and built elements [@pickett2017]. The integration of natural with social and built elements results in a diverse and unique array of ecosystems within the urban landscape. Throughout cities, the natural, physical, social, and built elements can benefit the people living there. Globally, urban populations continue to increase in part due to the nature of city's centralized design, which allows residents to fulfill many basic needs and access better services [@unitednations2019]. For example, living in a city can vastly increase the quality and quantity of services accessible to you, such as waste management, water treatment, and higher quality education [@unitednations2019]. Many benefits of cities are due to the social and built elements that are implemented. However, in addition to the benefits of urban built and social elements, the natural and physical elements of the city provide many benefits to urban dwellers. Most of the world's population currently lives in an urban area [@unitednations2019], meaning that the majority of people experience nature through the lens of the urban landscape. For example, benefits from urban trees to city residents exceed benefits from forest trees [@larouche2021]. Contact with urban nature results in greater overall well-being, more happiness, reduced mortality, and other mental and physical health benefits [@frumkin2017]. All nature, urban and non-urban, provides specific gifts and benefits to humans that we cannot receive from built elements. However, urban nature differs in an important way, management.  

Everything in our cities is managed by humans, including nature. For example, the composition of the urban forest is determined by a variety of stakeholders [@aronson2017]. Urban planners, residents, and developers all make decisions regarding management, which inevitably impact the density and species of trees that make up the urban forest. Often, the goal of urban nature management is to design spaces in a way that maximizes benefits to urban dwellers. However, depending on the stakeholder, maximizing human benefit can look very different [@salmond2016]. For example, municipal planners want to have low levels of maintenance and are often guided by ecologically determined "best practices" for planting, whereas residents may be trying to maximize benefits such as food production or aesthetic beauty. Further, management occurs on vastly different scales, with municipal governments attempting to manage at a city or landscape scale, whereas private land owners are often managing at a parcel level. Because of disparate interests and scales, attempting to manage urban nature in a holistic way that meets everyone's needs and benefits all stakeholders has been referred to as a "wicked" problem [@gaston2013].  

Despite being a commonly reiterated goal, cities in the Global North are not being designed or managed to maximize benefits to all stakeholders. Currently, we build and manage our cities under capitalist and settler-colonial systems. The prioritization of maximizing financial benefit to private businesses and individuals in combination with the legacy of settler-colonial ideals, most notably racism, has led to a deeply skewed and inequitable distribution of urban benefits [@ernstson2013]. Despite the hard and relentless work of many municipal government employees, activists, and NGOs to address the long-standing inequities of urban nature's benefits, there are still extremely harmful disparities in how the distribution, production, and delivery of urban nature's benefits occurs [@schell2020]. For example, the "luxury effect" is a well-proven theory in urban ecology where a large amount of variation in urban nature quantity and quality can be explained by the socioeconomic status of the neighbourhoods in question [@gerrish2018; @wu2014]. For example, the benefits received by urban parks, including but not limited to alleviating public health issues, is negatively correlated with the proportion of Black, Indigenous, and other racialized residents in the census tract in the United States [@hoover2020]. To maximize urban nature's benefits to the entire urban population, we need to critically engage with the prioritization of economic benefits and make our decisions based on other criteria, such as equity, compassion, and justice.  

Nature bestows many benefits and gifts on humans that interact with it, consciously or unconsciously. Often, the gifts that nature gives to humans are defined as "nature's contributions to people" or ecosystem services [@millenniumecosystemassessment2005; @diaz2015]. Ecosystem services improve human's quality of life. Depending on the particular service, humans often rely on ecosystem services for our survival [@millenniumecosystemassessment2005]. For example, the crop production is an ecosystem service that most humans rely on as our source of food. Ecosystem services can also enhance our lives, by providing benefits that we don't need to survive, but are still important to our health and allow us to thrive. For example, in China, living in a community with access to clean water can improve elderly individuals' mental health and aid in stress recovery [@chen2020]. Thus, managing urban nature for the production and delivery of ecosystem services is a common municipal goal. However, nature's impacts are not always beneficial [@roman2020; @salmond2016]. For example, urban greening can provide services such as air pollution and heat mitigation but it can also cause gentrification and resident displacement, ultimately acting as a disservice to the community [@roman2020]. The negative impacts of nature on human lives are often referred to as ecosystem disservices. The urban landscape is a complex and dynamic system that is made up of many ecosystem services and disservices.  

Ecosystem services are often categorized into four main groups, all of which provide humans with services that improve their quality of life. Based on the @millenniumecosystemassessment2005, the four categories of ecosystem services include provisioning services, regulating services, supporting services, and cultural services. In reality, many ecosystem services cross the boundaries of each group and can provide benefits in multiple categories. Provisioning services are defined as benefits that provide products from ecosystems, for example food provided through agriculture. Regulating services are defined as benefits that are obtained through the regulation of ecosystems, such as climate regulation from tree canopies. Supporting services are defined as services that are needed for overall ecosystem functioning, such as nutrient cycling. Finally, cultural services are defined as benefits obtained from ecosystems that are non-material in nature, for example, a sense of belonging. All four groups of ecosystem services provide different benefits to humans and all are required to improve quality of life.  

Managing urban nature to maximize benefits to all urban dwellers is a daunting task, however, an "ecosystem services" framework may allow us to attempt it [@bennett2017]. Ecosystem service management includes four different processes, capacity, pressure, demand, and flow [@villamagna2013]. Ecosystem service capacity is the ecosystem's ability to produce a service. Capacity is the easiest to quantify ecologically, and is often focused on by urban ecology studies. For example, stocking a river with fish will increase the population and improve that ecosystem's capacity for fishing yields. However, the provision of ecosystem services is not only dependent on the capacity of the ecosystem. We also must consider pressures, which include biophysical influences that change the ability of the ecosystem to provide the service. Pressures can change the capacity of an ecosystem to provide services. For example, overfishing is a pressure that can reduce population levels to a level where stable reproduction levels are no longer possible, thus changing the capacity of the river's provisioning services. Demand is the level of service that is required by society, and is notoriously difficult to quantify ecologically [@haase2014]. Demand can increase due to increased population, for example, higher population density in turn requires more food. However, demand also changes with individual values and culture. For example, if two neighbourhoods have the same population density but the culture of one values and requires fish as part of their more than the other, then the demand can differ even when the population density doesn't. Finally, flow is the amount of ecosystem services actually received by people. Flow is an integration of capacity, pressures, and demand. To truly deliver ecosystem services in a meaningful way in cities, we must take into account each process related to management.  

Regulating ecosystem services are particularly critical when managing cities [@villamagna2013]. The ecological footprint of a city often extends far beyond its borders, with many of the supplies and provisioning, cultural, and supporting ecosystem services required by the high population being provided from elsewhere [@gaston2013]. For example, many of the provisioning ecosystem services that urban residents need and enjoy are outsourced to surrounding agricultural areas. Similarly, cultural ecosystem services can be provided by nature found outside the city limits, such as National Parks. However, regulating services must be produced *in situ* [@sutherland2018]. The cooling benefits provided by tree canopies cannot be imported, nor can the clean water provided by the city's watershed. The nature of regulating services requires them to be built into the city's landscape. Thus, designing and managing urban nature to provide regulating ecosystem services is a key part of having a just and equitable city.  

The heterogeneity of cities lends another level of complexity to managing ecosystem services. Cities are highly dynamic and heterogeneous, varying on a uniquely fine-scale [@knapp2020; @ziter2018]. Delivery of ecosystem services changes across spatial and temporal [@pickett2017]. The effective and just delivery of ecosystem services requires an approach that can shift depending on the scale of interest. The capacity of the urban landscape to deliver ecosystem services is highly spatially heterogeneous. For example, ecosystem service capacity of the urban forest is often dependent on the species of trees planted. However, different stakeholders will plant different species, which can occur on a small scale, e.g. different homeowners planting different species in their yards. Spatial heterogeneity can also occur on larger scales, e.g. variation in species composition across different neighbourhoods [@ossola2019] or cities [@lin2019]. Thus, uncovering drivers behind ecosystem service capacity, demand, and flow requires a multi-scale approach. *Similarly, temporal variation also occurs on multiple scales. The delivery of ecosystem services can change on a fine-scale, for example across seasons, or on a much larger scale, for example across the time frame of city densification.*  

My proposed thesis will investigate spatial and temporal variation in the delivery of regulating ecosystem services by the urban forest...

\newpage
# Study Area(s)
My work will take place on the unceded and traditional lands of the Haudenosaunee and Mohawk peoples [@zotero-1439]. Before outlining my data collection and analysis methods, I believe it is important to acknowledge and outline my positionality. One's positionality refers to the space they occupy in relation to their research [@alcoff1988]. Discussing and acknowledging positionality is a widely accepted and encouraged part of scholarship for many disciplines, mainly in the social sciences [@england1994]. Natural science has so far gotten away without this important practice because of the belief that our research is "objective". However, my training and approach to the natural sciences is directly informed by my privilege, worldview, and experiences. As such, I believe that by outlining my biases and approach, I give context and credibility to the work I will do and provide a critical step in reproducible and transparent research. I am approaching this research as a descendent of white settler-colonial Europeans who grew up on the traditional and unceded homelands of the Haudenosaunee, Anishinaabe, and Attiwonderonk Peoples. My privilege as a cisgender, white, settler researcher directly informs the questions I ask and the science I produce. My training and approach to natural science is informed by a Eurocentric worldview, which means that I have been trained to view humans and nature as distinct entities and use a reductionist approach. My approach is not better or worse than others, however, it does inform how I will ask and answer questions in this system.



\newpage
### References
